name: flutter_flavor_example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_flavorizr: ^2.1.3

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    prod:
      app:
        name: "Prod App"

      android:
        applicationId: "com.shahi.flutter_flavor.prod"
        firebase:
          config: "/Users/shahi/Desktop/Flutter Projects/flutter_flavor_example/config/android/prod/google-services.json"

      ios:
        bundleId: "com.shahi.flutter_flavor.prod"

    dev:
      app:
        name: "Dev App"

      android:
        applicationId: "com.shahi.flutter_flavor.dev"
        firebase:
          config: "/Users/shahi/Desktop/Flutter Projects/flutter_flavor_example/config/android/dev/google-services.json"

      ios:
        bundleId: "com.shahi.flutter_flavor.dev"